apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::336349159477:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QTZN2SF2U9K6
      username: system:node:{{EC2PrivateDNSName}}
           - rolearn: arn:aws:iam::<336349159477>:role/UdacityFlaskDeployCBKubectlRole
       username: build
       groups:
         - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-06T11:35:38Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-06T11:35:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1480"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 21848d90-11b4-4b46-b3a6-80be0a0a3f23
